#!/usr/bin/env node
'use strict';

const fs = require('fs');
const XMLHttpRequest = require("xmlhttprequest").XMLHttpRequest;

module.exports = slackChannelLighthouseResult();

fs.readFile('file.txt', function(err, data) {
    if(err) {
        console.error(err);
        process.exit(1);
    }

    return sendSlack(data.toString())
});

function slackChannelLighthouseResult() {
    const _currentTime = Date.now();
    let _site = 'test'; // Generated by lighthouse or pharos
    let _siteResult = '30'; // Generated by lighthouse or pharos

    let data = JSON.stringify({"text": `Date: ${_currentTime} \n URL: ${_site} \n Result: ${_siteResult}`});

    return data;
}

function sendSlack(webHook) {
    const _request = new XMLHttpRequest();
    let _slack = slackChannelLighthouseResult();

    _request.open('POST', webHook, true);
    _request.setRequestHeader('Content-Type', 'application/json');
    _request.send(_slack);
}
